-- Research Lab Manager — Supabase schema
-- Run this once in the Supabase SQL editor for your project.
-- Safe to re-run: uses IF NOT EXISTS / OR REPLACE everywhere except on the
-- `alter publication` block (which will error harmlessly if already added).

-- ============================================================================
-- Tables
-- ============================================================================

create table if not exists public.team_members (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null default '',
  function_title text default '',
  email text default '',
  photo text default '',
  start_date text default '',
  is_active smallint default 1,
  ugent_id text default '',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.team_member_relationships (
  id bigint generated by default as identity primary key,
  member_id bigint not null unique references public.team_members(id) on delete cascade,
  parent_id bigint not null references public.team_members(id) on delete cascade
);

create table if not exists public.phd_trackers (
  id bigint generated by default as identity primary key,
  team_member_id bigint not null references public.team_members(id) on delete cascade,
  phd_start_date text not null,
  expected_end_date text not null,
  status text default 'on_track',
  milestones text default '[]',
  chapters text default '[]',
  notes text default '',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  name text not null,
  description text default '',
  funding text default '',
  budget double precision default 0,
  person_months double precision default 0,
  status text default 'active',
  start_date text default '',
  end_date text default '',
  color text default '#4a90d9',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.project_members (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  team_member_id bigint not null references public.team_members(id) on delete cascade,
  role_in_project text default ''
);

create table if not exists public.deliverables (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  title text not null,
  description text default '',
  due_date text default '',
  status text default 'pending',
  assigned_to bigint references public.team_members(id) on delete set null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.meeting_notes (
  id bigint generated by default as identity primary key,
  title text not null,
  date text not null,
  content text default '',
  project_id bigint references public.projects(id) on delete set null,
  phd_tracker_id bigint references public.phd_trackers(id) on delete set null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.meeting_attendees (
  id bigint generated by default as identity primary key,
  meeting_id bigint not null references public.meeting_notes(id) on delete cascade,
  team_member_id bigint not null references public.team_members(id) on delete cascade
);

create table if not exists public.kanban_tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  description text default '',
  column_name text not null default 'todo',
  position integer not null default 0,
  color text default '',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ============================================================================
-- updated_at trigger
-- ============================================================================

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

do $$
declare
  t text;
begin
  for t in select unnest(array[
    'team_members', 'phd_trackers', 'projects',
    'deliverables', 'meeting_notes', 'kanban_tasks'
  ])
  loop
    execute format(
      'drop trigger if exists set_updated_at on public.%I;
       create trigger set_updated_at before update on public.%I
       for each row execute function public.set_updated_at();',
      t, t
    );
  end loop;
end$$;

-- ============================================================================
-- Views (mirror the join queries the app used to do client-side)
-- security_invoker = true so RLS on underlying tables applies.
-- ============================================================================

create or replace view public.phd_trackers_with_member
with (security_invoker = true) as
select p.*,
       t.name  as member_name,
       t.role  as member_role,
       t.photo as member_photo
from public.phd_trackers p
join public.team_members t on p.team_member_id = t.id;

create or replace view public.deliverables_with_assignee
with (security_invoker = true) as
select d.*,
       t.name  as assignee_name,
       p.name  as project_name,
       p.color as project_color
from public.deliverables d
left join public.team_members t on d.assigned_to = t.id
join public.projects p on d.project_id = p.id;

create or replace view public.meeting_notes_with_details
with (security_invoker = true) as
select m.*,
       p.name as project_name,
       t.name as phd_member_name
from public.meeting_notes m
left join public.projects p on m.project_id = p.id
left join public.phd_trackers pt on m.phd_tracker_id = pt.id
left join public.team_members t on pt.team_member_id = t.id;

create or replace view public.project_members_with_name
with (security_invoker = true) as
select pm.*,
       t.name as member_name
from public.project_members pm
join public.team_members t on pm.team_member_id = t.id;

-- ============================================================================
-- Row-Level Security
-- Single-lab model: any signed-in user can read and write everything.
-- Tighten later by introducing a profiles table with roles if needed.
-- ============================================================================

do $$
declare
  t text;
begin
  for t in select unnest(array[
    'team_members', 'team_member_relationships', 'phd_trackers',
    'projects', 'project_members', 'deliverables',
    'meeting_notes', 'meeting_attendees', 'kanban_tasks'
  ])
  loop
    execute format('alter table public.%I enable row level security;', t);
    execute format('drop policy if exists "auth read"  on public.%I;', t);
    execute format('drop policy if exists "auth write" on public.%I;', t);
    execute format(
      'create policy "auth read"  on public.%I for select to authenticated using (true);',
      t
    );
    execute format(
      'create policy "auth write" on public.%I for all    to authenticated using (true) with check (true);',
      t
    );
  end loop;
end$$;

-- ============================================================================
-- One-shot helper: bumps each table's ID sequence past the highest existing id.
-- Used by the JSON migration importer after it inserts rows with explicit IDs.
-- ============================================================================

create or replace function public.reset_id_sequences()
returns void language plpgsql security invoker as $$
declare
  t text;
begin
  for t in select unnest(array[
    'team_members', 'team_member_relationships', 'phd_trackers',
    'projects', 'project_members', 'deliverables',
    'meeting_notes', 'meeting_attendees', 'kanban_tasks'
  ])
  loop
    execute format(
      'select setval(pg_get_serial_sequence(''public.%1$s'', ''id''),
                     coalesce((select max(id) from public.%1$s), 0) + 1,
                     false)',
      t
    );
  end loop;
end$$;

grant execute on function public.reset_id_sequences() to authenticated;

-- ============================================================================
-- Realtime publication
-- Enables postgres_changes broadcasts so colleagues see edits live.
-- ============================================================================

do $$
declare
  t text;
begin
  for t in select unnest(array[
    'team_members', 'team_member_relationships', 'phd_trackers',
    'projects', 'project_members', 'deliverables',
    'meeting_notes', 'meeting_attendees', 'kanban_tasks'
  ])
  loop
    begin
      execute format('alter publication supabase_realtime add table public.%I;', t);
    exception when duplicate_object then
      -- table already in publication
      null;
    end;
  end loop;
end$$;
